services:
  - type: web
    name: backend
    env: node
    buildCommand: npm install --build-from-source
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: SQLITE3_BUILD_FROM_SOURCE
        value: "true"  # Força a compilação do sqlite3
      - key: FORCE_SSL
        value: "true"
    plan: free
    region: us
